name: CI Workflow (PHP Composer)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install --dev

      - name: Run tests
        run: composer run test

      - name: Build and Test with Docker
        run: |
          docker build -t my-app .
          docker run my-app bash -c "composer install && vendor/bin/phpunit"
